# Generated by Django 2.1.5 on 2019-01-25 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LearningCentre', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learningcentresubcategories',
            old_name='category',
            new_name='category_id',
        ),
        migrations.RenameField(
            model_name='learningcentresubcategoriesquestionanswer',
            old_name='category',
            new_name='category_id',
        ),
        migrations.RenameField(
            model_name='learningcentresubcategoriesquestionanswer',
            old_name='subcategory',
            new_name='subcategory_id',
        ),
    ]
