# Generated by Django 2.1.5 on 2019-02-27 13:25

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('LearningCentre', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningcentresubcategoriesquestionanswer',
            name='question',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
