# Generated by Django 2.1.5 on 2019-01-24 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20190124_0806'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockDetailToday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('today_up', models.FloatField()),
                ('today_down', models.FloatField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Stock')),
            ],
        ),
    ]
