# Generated by Django 2.1.5 on 2019-01-24 14:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_stockdetailtoday'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockdetailtoday',
            name='today',
            field=models.CharField(default=datetime.datetime(2019, 1, 24, 14, 59, 28, 541236), max_length=100),
        ),
    ]
