# Generated by Django 2.1.5 on 2019-01-25 08:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_stockdetailtoday_today'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
                ('answer', models.CharField(max_length=10000)),
            ],
        ),
        migrations.AlterField(
            model_name='stockdetailtoday',
            name='today',
            field=models.CharField(default=datetime.datetime(2019, 1, 25, 8, 58, 14, 409638), max_length=100),
        ),
        migrations.AddField(
            model_name='stockquestion',
            name='stock_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.StockDetailToday'),
        ),
    ]
