# Generated by Django 2.1.5 on 2019-01-25 09:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20190125_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockquestion',
            name='stock',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='company.Stock'),
        ),
        migrations.AlterField(
            model_name='stockdetailtoday',
            name='today',
            field=models.CharField(default=datetime.datetime(2019, 1, 25, 9, 3, 43, 580617), max_length=100),
        ),
    ]
