# Generated by Django 2.1.5 on 2019-01-25 10:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_auto_20190125_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdetailtoday',
            name='today',
            field=models.CharField(default=datetime.datetime(2019, 1, 25, 10, 1, 29, 933365), max_length=100),
        ),
    ]
