# Generated by Django 2.1.5 on 2019-02-27 13:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0032_auto_20190227_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdetailtoday',
            name='today',
            field=models.CharField(default=datetime.datetime(2019, 2, 27, 13, 8, 31, 413411), max_length=100),
        ),
    ]
