# Generated by Django 2.1.5 on 2019-02-27 13:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0039_auto_20190227_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockdetailtoday',
            name='today',
            field=models.CharField(default=datetime.datetime(2019, 2, 27, 13, 25, 52, 208943), max_length=100),
        ),
    ]
